USE CcRequesterSetad
GO
SELECT TOP(10) * FROM ViewMonitoringTv

--SELECT *
SELECT COLUMN_NAME , DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ViewMonitoringTv'
--ORDER BY COLUMN_NAME
ORDER BY ORDINAL_POSITION

SELECT * FROM Tbl_EndJobState order by EndJobStateId
