USE CcRequesterSetad
GO
SELECT TOP(2) * FROM TblTamirRequest
GO
SELECT TOP(2) * FROM TblRequest
GO

select top 100 MPFeederCode AS Code ,* from Tbl_MPFeeder 
where MPFeederCode IS NOT NULL

SELECT COLUMN_NAME , DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TblTamirRequest' 
		AND COLUMN_NAME LIKE '%Id'
		--AND COLUMN_NAME NOT LIKE '%Id'
--ORDER BY COLUMN_NAME
ORDER BY ORDINAL_POSITION


SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%request%'
	--AND TABLE_TYPE = 'BASE TABLE'
	AND TABLE_TYPE = 'VIEW'
