USE CcRequesterSetad
GO
SELECT TOP(10) * FROM TblLPPostLoad
GO
SELECT TOP(10) * FROM Tbl_LPPost
GO
SELECT TOP(10) * FROM Tbl_MPFeeder
GO
SELECT TOP(10) * FROM Tbl_MPPost
GO
SELECT TOP(10) * FROM Tbl_LPPostType
GO
SELECT TOP(10) * FROM Tbl_Area
GO
SELECT TOP(10) * FROM Tbl_Temperature
GO
SELECT TOP(10) * FROM Tbl_Altitude


SELECT COLUMN_NAME , DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Tbl_Area' AND COLUMN_NAME LIKE '%alt%'
--ORDER BY COLUMN_NAME
ORDER BY ORDINAL_POSITION


SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%temp%'
--ORDER BY COLUMN_NAME
--ORDER BY ORDINAL_POSITION



--Test
EXEC spGetReport_LPPostLoadBalance '11-0109hg', '1387/01/01', '1393/01/01'

--UPDATE TblLPPostLoad SET IsTakFaze = 1 WHERE LPPostLoadId IN (30101512,30091068,30111991,30119815)
UPDATE TblLPPostLoad SET IsTakFaze = 0 WHERE LPPostId = 10050368

select p.LPPostCode , p.LPPostName, PL.IsTakFaze AS TAK,PL.* from  TblLPPostLoad PL 
INNER JOIN Tbl_LPPost P ON P.LPPostId = PL.LPPostId
where PL.LPPostId = 10050368

select convert(decimal(10, 2), 235.415);